remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 

gem "github-pages", group: :jekyll_plugins

title: [Eric Chen]
description: [This is my homepage]

show_downloads: ["true"]
